-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PSYCHOSOCIAL_PROFILE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PSYCHOSOCIAL_PROFILE_PDF_EXPORTED';

-- AlterTable
ALTER TABLE "PsychosocialProfile"
ADD COLUMN "medicalConsent" BOOLEAN NOT NULL DEFAULT false;
